//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Probadva
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Формир распр.
    /// </summary>
    // *** Start programmer edit section *** (ФормирРаспр CustomAttributes)

    // *** End programmer edit section *** (ФормирРаспр CustomAttributes)
    [AutoAltered()]
    [Caption("Формирование распределения")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ФормирРаспрE", new string[] {
            "Дата as \'Дата\'",
            "НомерДокРаспред as \'Номер документа распределения\'",
            "ДокумПостав as \'Номер документа поставки\'",
            "ДокумПостав.Клиенты.Заказчик as \'Заказчик\'",
            "ДокумПостав.Клиенты.АдресПоставки as \'Адрес поставки\'",
            "ДокумПостав.Клиенты.Телефон as \'Телефон\'",
            "СписокБарж as \'Номер баржи\'",
            "ПунктПогрузки as \'Адрес погрузки\'",
            "СписокКонтей as \'Номер контейнера\'"})]
    [MasterViewDefineAttribute("ФормирРаспрE", "ДокумПостав", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "НомерДогов")]
    [MasterViewDefineAttribute("ФормирРаспрE", "СписокБарж", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "НомерБаржи")]
    [MasterViewDefineAttribute("ФормирРаспрE", "ПунктПогрузки", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Адрес")]
    [MasterViewDefineAttribute("ФормирРаспрE", "СписокКонтей", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "НомерКонтей")]
    [View("ФормирРаспрL", new string[] {
            "Дата as \'Дата\'",
            "НомерДокРаспред as \'Номер документа распределения\'",
            "СписокБарж.НомерБаржи as \'Номер баржи\'",
            "ДокумПостав.НомерДогов as \'Номер документа поставки\'",
            "ПунктПогрузки.Адрес as \'Адрес погрузки\'",
            "СписокКонтей.НомерКонтей as \'Номер контейнера\'"})]
    public class ФормирРаспр : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fДата;
        
        private int fНомерДокРаспред;
        
        private IIS.Probadva.ПунктПогрузки fПунктПогрузки;
        
        private IIS.Probadva.СписокКонтей fСписокКонтей;
        
        private IIS.Probadva.ДокумПостав fДокумПостав;
        
        private IIS.Probadva.СписокБарж fСписокБарж;
        
        // *** Start programmer edit section *** (ФормирРаспр CustomMembers)

        // *** End programmer edit section *** (ФормирРаспр CustomMembers)

        
        /// <summary>
        /// Дата.
        /// </summary>
        // *** Start programmer edit section *** (ФормирРаспр.Дата CustomAttributes)

        // *** End programmer edit section *** (ФормирРаспр.Дата CustomAttributes)
        public virtual System.DateTime Дата
        {
            get
            {
                // *** Start programmer edit section *** (ФормирРаспр.Дата Get start)

                // *** End programmer edit section *** (ФормирРаспр.Дата Get start)
                System.DateTime result = this.fДата;
                // *** Start programmer edit section *** (ФормирРаспр.Дата Get end)

                // *** End programmer edit section *** (ФормирРаспр.Дата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ФормирРаспр.Дата Set start)

                // *** End programmer edit section *** (ФормирРаспр.Дата Set start)
                this.fДата = value;
                // *** Start programmer edit section *** (ФормирРаспр.Дата Set end)

                // *** End programmer edit section *** (ФормирРаспр.Дата Set end)
            }
        }
        
        /// <summary>
        /// НомерДокРаспред.
        /// </summary>
        // *** Start programmer edit section *** (ФормирРаспр.НомерДокРаспред CustomAttributes)

        // *** End programmer edit section *** (ФормирРаспр.НомерДокРаспред CustomAttributes)
        public virtual int НомерДокРаспред
        {
            get
            {
                // *** Start programmer edit section *** (ФормирРаспр.НомерДокРаспред Get start)

                // *** End programmer edit section *** (ФормирРаспр.НомерДокРаспред Get start)
                int result = this.fНомерДокРаспред;
                // *** Start programmer edit section *** (ФормирРаспр.НомерДокРаспред Get end)

                // *** End programmer edit section *** (ФормирРаспр.НомерДокРаспред Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ФормирРаспр.НомерДокРаспред Set start)

                // *** End programmer edit section *** (ФормирРаспр.НомерДокРаспред Set start)
                this.fНомерДокРаспред = value;
                // *** Start programmer edit section *** (ФормирРаспр.НомерДокРаспред Set end)

                // *** End programmer edit section *** (ФормирРаспр.НомерДокРаспред Set end)
            }
        }
        
        /// <summary>
        /// Формир распр.
        /// </summary>
        // *** Start programmer edit section *** (ФормирРаспр.ДокумПостав CustomAttributes)

        // *** End programmer edit section *** (ФормирРаспр.ДокумПостав CustomAttributes)
        [PropertyStorage(new string[] {
                "ДокумПостав"})]
        [NotNull()]
        public virtual IIS.Probadva.ДокумПостав ДокумПостав
        {
            get
            {
                // *** Start programmer edit section *** (ФормирРаспр.ДокумПостав Get start)

                // *** End programmer edit section *** (ФормирРаспр.ДокумПостав Get start)
                IIS.Probadva.ДокумПостав result = this.fДокумПостав;
                // *** Start programmer edit section *** (ФормирРаспр.ДокумПостав Get end)

                // *** End programmer edit section *** (ФормирРаспр.ДокумПостав Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ФормирРаспр.ДокумПостав Set start)

                // *** End programmer edit section *** (ФормирРаспр.ДокумПостав Set start)
                this.fДокумПостав = value;
                // *** Start programmer edit section *** (ФормирРаспр.ДокумПостав Set end)

                // *** End programmer edit section *** (ФормирРаспр.ДокумПостав Set end)
            }
        }
        
        /// <summary>
        /// Формир распр.
        /// </summary>
        // *** Start programmer edit section *** (ФормирРаспр.ПунктПогрузки CustomAttributes)

        // *** End programmer edit section *** (ФормирРаспр.ПунктПогрузки CustomAttributes)
        [PropertyStorage(new string[] {
                "ПунктПогрузки"})]
        [NotNull()]
        public virtual IIS.Probadva.ПунктПогрузки ПунктПогрузки
        {
            get
            {
                // *** Start programmer edit section *** (ФормирРаспр.ПунктПогрузки Get start)

                // *** End programmer edit section *** (ФормирРаспр.ПунктПогрузки Get start)
                IIS.Probadva.ПунктПогрузки result = this.fПунктПогрузки;
                // *** Start programmer edit section *** (ФормирРаспр.ПунктПогрузки Get end)

                // *** End programmer edit section *** (ФормирРаспр.ПунктПогрузки Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ФормирРаспр.ПунктПогрузки Set start)

                // *** End programmer edit section *** (ФормирРаспр.ПунктПогрузки Set start)
                this.fПунктПогрузки = value;
                // *** Start programmer edit section *** (ФормирРаспр.ПунктПогрузки Set end)

                // *** End programmer edit section *** (ФормирРаспр.ПунктПогрузки Set end)
            }
        }
        
        /// <summary>
        /// Формир распр.
        /// </summary>
        // *** Start programmer edit section *** (ФормирРаспр.СписокБарж CustomAttributes)

        // *** End programmer edit section *** (ФормирРаспр.СписокБарж CustomAttributes)
        [PropertyStorage(new string[] {
                "СписокБарж"})]
        [NotNull()]
        public virtual IIS.Probadva.СписокБарж СписокБарж
        {
            get
            {
                // *** Start programmer edit section *** (ФормирРаспр.СписокБарж Get start)

                // *** End programmer edit section *** (ФормирРаспр.СписокБарж Get start)
                IIS.Probadva.СписокБарж result = this.fСписокБарж;
                // *** Start programmer edit section *** (ФормирРаспр.СписокБарж Get end)

                // *** End programmer edit section *** (ФормирРаспр.СписокБарж Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ФормирРаспр.СписокБарж Set start)

                // *** End programmer edit section *** (ФормирРаспр.СписокБарж Set start)
                this.fСписокБарж = value;
                // *** Start programmer edit section *** (ФормирРаспр.СписокБарж Set end)

                // *** End programmer edit section *** (ФормирРаспр.СписокБарж Set end)
            }
        }
        
        /// <summary>
        /// Формир распр.
        /// </summary>
        // *** Start programmer edit section *** (ФормирРаспр.СписокКонтей CustomAttributes)

        // *** End programmer edit section *** (ФормирРаспр.СписокКонтей CustomAttributes)
        [PropertyStorage(new string[] {
                "СписокКонтей"})]
        [NotNull()]
        public virtual IIS.Probadva.СписокКонтей СписокКонтей
        {
            get
            {
                // *** Start programmer edit section *** (ФормирРаспр.СписокКонтей Get start)

                // *** End programmer edit section *** (ФормирРаспр.СписокКонтей Get start)
                IIS.Probadva.СписокКонтей result = this.fСписокКонтей;
                // *** Start programmer edit section *** (ФормирРаспр.СписокКонтей Get end)

                // *** End programmer edit section *** (ФормирРаспр.СписокКонтей Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ФормирРаспр.СписокКонтей Set start)

                // *** End programmer edit section *** (ФормирРаспр.СписокКонтей Set start)
                this.fСписокКонтей = value;
                // *** Start programmer edit section *** (ФормирРаспр.СписокКонтей Set end)

                // *** End programmer edit section *** (ФормирРаспр.СписокКонтей Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ФормирРаспрE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ФормирРаспрE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ФормирРаспрE", typeof(IIS.Probadva.ФормирРаспр));
                }
            }
            
            /// <summary>
            /// "ФормирРаспрL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ФормирРаспрL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ФормирРаспрL", typeof(IIS.Probadva.ФормирРаспр));
                }
            }
        }
    }
}
